//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.18 at 02:37:29 AM NZST 
//


package localhost._8080.xml.gcdc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.xml.gcdc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.xml.gcdc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GcdSumRequest }
     * 
     */
    public GcdSumRequest createGcdSumRequest() {
        return new GcdSumRequest();
    }

    /**
     * Create an instance of {@link GcdRequest }
     * 
     */
    public GcdRequest createGcdRequest() {
        return new GcdRequest();
    }

    /**
     * Create an instance of {@link GcdResponse }
     * 
     */
    public GcdResponse createGcdResponse() {
        return new GcdResponse();
    }

    /**
     * Create an instance of {@link GcdSumResponse }
     * 
     */
    public GcdSumResponse createGcdSumResponse() {
        return new GcdSumResponse();
    }

    /**
     * Create an instance of {@link GcdListRequest }
     * 
     */
    public GcdListRequest createGcdListRequest() {
        return new GcdListRequest();
    }

    /**
     * Create an instance of {@link GcdListResponse }
     * 
     */
    public GcdListResponse createGcdListResponse() {
        return new GcdListResponse();
    }

}
